### ISSUE TITLE
Choosing Body Parts

### ISSUE THREAD

**Issue by jacobk14** [YttriLab/B-SOID#11]
I am attempting to analyze the results of a DLC model that I have already created, so I had not seen the B-SOID instructions when I made it. In the config file, it says that you have to have at least 6 body parts (Snout/heat, shoulder1/forepaw, body center, etc...). Does this mean if I don't have a body part labeled "body center", then the analysis won't work?

**Comment by runninghsus** [comment]
Hi @jacobk14 

Thank you for your interest in B-SOiD!
No, that just means that the [t-SNE version](https://github.com/YttriLab/B-SOID/blob/master/docs/python3_tutorial.md) (the one you're talking about) takes a pre-defined 6 body parts outlining the animal to compute metrics such as distance, angle, and speed. The only thing that you have to change is the index that follows, as the algorithm only looks for those. For example, if your snout is the last to be labeled, as opposed to the first, you'll want to change that **0** to **5**. You will need the presets indexed for the code to run without error - snout/head, shoulder/forepaw, hip/hindpaw, and tail-base. You can add more, such as body center, for indexing, but it just won't be reading that. 

_In other words, if you have the 6 body parts (again, not necessarily named that way, but get at similar locations on the animal) - **snout/head, shoulder/forepaw, hip/hindpaw, and tail-base**, then go ahead and use this. The reason for these body parts to be required is that the 7 features (see [preprint](https://www.biorxiv.org/content/10.1101/770271v2)) are hardcoded in._

If, however, you have a different view as bottom-up/top-down, and/or have fewer/more body parts labeled, I would recommend the UMAP version (specifically the [bsoid_app](https://github.com/YttriLab/B-SOID/blob/master/docs/bsoid_app_init.md), as it contains the same computation and more utilities than the [bsoid_umap](https://github.com/YttriLab/B-SOID/blob/master/docs/bsoid_umap_tutorial.md) does). 

Thank you again for opening this issue, best of luck!

**Comment by jacobk14** [comment]
Hi, Thank you for your response. I have opened the app; however, I am unsure of which 3 .csv files I am supposed to place in the "subdirectories" blanks on the app from my deeplabcut project folder.  The only one I can think of is the DLC_resnet50_ExerciseJun26shuffle1_52500-results.csv file within the evaluation-results folder.

**Comment by runninghsus** [comment]
The subdirectories are the folders that contains all the csv files you wish to train. If you only have 1 folder, then reduce the number of subdirectories to 1. 
In other words, it'll load all .csv files from the folder (subdirectory). For example, if you have the deeplabcut project folder /Users/jacob_deeplabcut that contains the DLC_resnet50_ExerciseJun26shuffle1_52500-results.csv then your BASE_PATH will be /Users, and your subdirectory will be /jacob_deeplabcut

**Comment by jacobk14** [comment]
Thank you! I have made it through the first few steps. In the section "Making sense of these behaviors", what does it mean by enter the testing subdirectory within the base path. It results in a drop-down menu to choose a csv file, but is it the original csv file from the deeplabcut project folder or does it mean one of the csv files that were created by the BSOID app?

**Comment by runninghsus** [comment]
If you selected "Generate predictions and corresponding videos" - you will be prompted to pick a csv file and mp4 file to generate videos to make sense of the groups. Select csv will be the original csv file, and make sure that your mp4 corresponds to the csv.
If you selected "Bulk process csvs" - you will be prompted to run predictions on the entire folders. One usually runs this after they made sense of what "group 1" is.

**Comment by jacobk14** [comment]
I selected "generate predictions and corresponding videos" and the corresponding .csv and .mp4 files. After I clicked "predict labels and generate example videos", it said, "Done frameshift predicting".  I am unsure what to do next though. The mp4 folder where I believe the example video should have been created is empty, and there are no more next steps that appeared in the app.

**Comment by runninghsus** [comment]
It will be easier for me to debug with screenshots from you. Could you join our slack channel? 
https://join.slack.com/t/b-soid/shared_invite/zt-dksalgqu-Eix8ZVYYFVVFULUhMJfvlw
