### ISSUE TITLE
Classification using the UMAP+HDBSCAN version of B-SOID has incorrect preprocessing?

### ISSUE THREAD

**Issue by Thalaivar** [YttriLab/B-SOID#12]
The `bsoid_extract()` function used in `bsoid_umap/classify.py` results in features with more dimensions than I began with
https://github.com/YttriLab/B-SOID/blob/2feec9ea46f39a7d99d4b2e458b98d13c98ae6aa/bsoid_umap/classify.py#L16

Using the same features mentioned in `bsoid_py/config/LOCAL_CONFIG.py`, the data should be 7-D, however the output of the above is 36-D. I swapped out the function for the one from `bsoid_py` and it works fine. The model that is trained in `bsoid_umap/train.py` is trained on 7-D features, so clearly this presents a problem

**Comment by runninghsus** [comment]
Hi can you provide more details? There was a bug before but the current version should have fixed that.

**Comment by Thalaivar** [comment]
> Hi can you provide more details? There was a bug before but the current version should have fixed that.

Sorry, I have added the details to the issue

**Comment by runninghsus** [comment]
bsoid_py extracts 7 defined features. bsoid_umap takes all pairs into consideration (n squared). You have to either run bsoid_py (7) or bsoid_umap (n2).
If you want to run umap + hdbscan on 7 features, let me know. There are a few things you would need to fix and might be good to discuss this over slack.

**Comment by Thalaivar** [comment]
> Hi can you provide more details? There was a bug before but the current version should have fixed that.

I think I might now why I am facing this issue. Let me give you some context here, I was using the t-SNE version of the algorithm, but have now switched to the UMAP version. Since I had a lot of data to preprocess, I saved the output of `likelihoodpreprocessing.py` and `bsoid_tsne()` so that I could use them directly. It is these saved features that I used to train my model in the UMAP version (meaning that I bypassed the `bsoid_umap/utils/likelihoodpreprocessing.py` and `bsoid_feats()` in ``bsoid_umap\train.py`). I then run my test csv file through the normal pipeline for `bsoid_umap`, i.e. through all the methods in `bsoid_umap\classify.py`

Could this be the cause for the mismatch??

**Comment by Thalaivar** [comment]
> bsoid_py extracts 7 defined features. bsoid_umap takes all pairs into consideration (n squared). You have to either run bsoid_py (7) or bsoid_umap (n2).

That settles it then! So much for my desire to save time :(

> If you want to run umap + hdbscan on 7 features, let me know. There are a few things you would need to fix and might be good to discuss this over slack.
Sure! I have some questions about the differences between the UMAP and t-SNE versions too if that's okay. How should we connect? Email?

**Comment by runninghsus** [comment]
Sorry about that! I'd be willing to help if you think 7 features (instead of 36) is best for your study!
Here's the slack link: https://join.slack.com/t/b-soid/shared_invite/zt-dksalgqu-Eix8ZVYYFVVFULUhMJfvlw
