### ISSUE TITLE
are logging messages correct in bsoid_extract?

### ISSUE THREAD

**Issue by kevinbolding** [YttriLab/B-SOID#14]
In bsoid_extract there are nested loops over n, s, and k

The position the following logging message means that it is repeated n*s times. 
6 times for each "n" in the case of a 60 FPS input.

logging.info('Done integrating features into 100ms bins from CSV file {}.'.format(n + 1))

In trying to understand this peculiarity I concluded that both n and s are looping over "offsets" rather than CSV files.

It seems that bsoid_extract receives all the 'offset' versions for one CSV file, process those, and would therefore only process one CSV file per call, which is why we are looping over CSV files in bsoid_frameshift.

It's not entirely clear to me yet why we need to loop over n and s, but I feel fairly certain that at least the logging message is incorrect.

**Comment by runninghsus** [comment]
HI @kevinbolding 

You are absolutely correct. The message is not accurate when doing frameshift, I just used the same function so it prints that automatically. Looping over offsets is a way to get back to the framerate while still integrating movement trajectory over time.
