### ISSUE TITLE
Potential typo in bsoid_py feature extraction?

### ISSUE THREAD

**Issue by Killian604** [YttriLab/B-SOID#15]
**File to be examined**:

- bsoid_py/classify.py

**Function to be examined**:

- bsoid_extract()

**Issue**: 

Upon reviewing the code responsible for feature engineering (here called "feature extraction"), there seems to be an anomaly for how an intermediate feature is calculated. See variable `cfp`. Below is an excerpt of the current state:
```
        cfp = np.vstack(((data[m][:, 2 * bodyparts.get('Forepaw/Shoulder1')] +
                          data[m][:, 2 * bodyparts.get('Forepaw/Shoulder2')]) / 2,
                         (data[m][:, 2 * bodyparts.get('Forepaw/Shoulder1') + 1] +
                          data[m][:, 2 * bodyparts.get('Forepaw/Shoulder1') + 1]) / 2)).T
```

Look at the final two lines in the 4-line code excerpt above. It appears as though calculating the average y-value between the Forepaws/Shoulders is calculated on only Forepaw/Shoulder1 instead of the average between Forepaw/Shoulder1 and Forepaw/Shoulder2. I would like to suggestion a small amendment:

```
        cfp = np.vstack(((data[m][:, 2 * bodyparts.get('Forepaw/Shoulder1')] +
                          data[m][:, 2 * bodyparts.get('Forepaw/Shoulder2')]) / 2,
                         (data[m][:, 2 * bodyparts.get('Forepaw/Shoulder1') + 1] +
                          data[m][:, 2 * bodyparts.get('Forepaw/Shoulder2') + 2]) / 2)).T
```

The only diff between code chunks (where the actual copy/paste is on top, suggested edit is on the bottom) is on the final line. Let me know if this is indeed an issue and/or if a different solution is necessary to remedy this. Thank you for your time.

**Comment by runninghsus** [comment]
Hi @Killian604 

Good catch! Will update that.
