### ISSUE TITLE
cannot load and preprocess data

### ISSUE THREAD

**Issue by kylecnewton** [YttriLab/B-SOID#20]
Hi,

I am running Win10 and successfully installed B-SOIDv2 but cannot load and preprocess data. Thanks1

Kyle

Here is the error message:

IndexError: arrays used as indices must be of integer (or boolean) type
Traceback:
File "c:\users\fish_behavior\.conda\envs\bsoid_v2\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Fish_Behavior\Desktop\B-SOID-v2\B-SOID\bsoid_app.py", line 42, in <module>
    processor.compile_data()
File "C:\Users\Fish_Behavior\Desktop\B-SOID-v2\B-SOID\bsoid_app\data_preprocess.py", line 104, in compile_data
    file_j_processed, p_sub_threshold = adp_filt(file_j_df, self.pose_chosen)
File "C:\Users\Fish_Behavior\Desktop\B-SOID-v2\B-SOID\bsoid_app\bsoid_utilities\likelihoodprocessing.py", line 87, in adp_filt
    datax = curr_df1[1:, np.array(xIndex)]

**Comment by runninghsus** [comment]
Hi,

Could you share a screenshot? Looks like file loading issue. 
What pose-estimation software are you using? And what was the file extension (.csv, .h5, or .json)?

**Comment by kylecnewton** [comment]
DLC multi animal but it is only one larval fish. Files are csv but I could try the original H5

<img width="1146" alt="Screenshot 2020-12-01 145249" src="https://user-images.githubusercontent.com/48524603/100795685-0dface00-33e5-11eb-9689-efdddd00f004.png">
<img width="1157" alt="Screenshot 2020-12-01 145333" src="https://user-images.githubusercontent.com/48524603/100795690-0f2bfb00-33e5-11eb-821e-f57f010d9ad1.png">

**Comment by runninghsus** [comment]
Ah, i think they changed the number of header rows to deal with multianimal stuff (the identified pose to include is capturing the wrong header row from what I can see). Could you share a screenshot of the headers so I can include that option?
Or better yet, if it's not too troublesome, could you email me a h5 or csv file?
I believe h5 will throw the same error.

**Comment by kylecnewton** [comment]
sure I will email both H5 and csv. What email address?

**Comment by runninghsus** [comment]
https://join.slack.com/t/b-soid/shared_invite/zt-dksalgqu-Eix8ZVYYFVVFULUhMJfvlw
It might be safer to share via slack.
