### ISSUE TITLE
Effects of Different Clustering Algorithms

### ISSUE THREAD

**Issue by Jameschen7** [YttriLab/B-SOID#25]
Hi there,

Thanks so much for your release!

I am working on a rat behavior analysis lab, and I have adapted part of your python code to train an SVM to predict behavioral labels of rats based on a TSNE algorithm. Since I borrowed your code a long time ago, I notice that you change your clustering algorithm from different versions of TSNE to a combination of UMAP and HDBSCAN.

I wonder whether I should update my code as well, so is it possible for you to share your view of how does each clustering algorithm affects the interpretability of the resultant behavioral labels? Here for interpretability, I mean whether the label represents meaningful behaviors.

Thank you so much for time,
James

**Comment by djanders19** [comment]
James, I'm not sure entirely what lab's reasoning was for updating to UMAP, but it might have something to do with the fact that there's some controversy around clustering t-SNE data (see [this ](https://umap-learn.readthedocs.io/en/latest/clustering.html)page and the linked StackOverflow thread in the first paragraph). That page also goes into using UMAP with HDBSCAN.

[This ](https://github.com/lmcinnes/umap/issues/25) discussion also may be of interest. Basically, UMAP is less likely than t-SNE to create artificial subclusters and better preserves density, which is important when running a density-based clustering algorithm.

Given that I'm not really sure what your code looks like (I've only worked with the UMAP version of BSOID) I don't know if that's relevant to your question, but hopefully provides some stuff to consider. Eric and Alex, chime in if I'm talking nonsense.

**Comment by Jameschen7** [comment]
Hi David,

Thanks for your response. Your comment and the links give me more insight into the advantages of UMAP over T-SNE. I will definitely take it into consideration.

**Comment by runninghsus** [comment]
Closed due to answer provided by @djanders19 and inactivity.
