### ISSUE TITLE
NotADirectoryError [Win267]

### ISSUE THREAD

**Issue by calebvogt** [YttriLab/B-SOID#26]
OS: Windows 10
Version: B-SOiD 2.0

Issue: I have just started exploring using B-SOID, although I have read the pre print and explored the github. I can't seem to get past the first step of loading a video and h5 file in the streamline web app (see screenshot)

I thought it might have to do with the whitespace in my file name (something I should probably get around to changing), but it doesnt seem to be an issue in assigning a root directory step. 

Any thoughts on what I could do to move forward? Thanks in advance for your help, and thanks for the awesome open source code!

![image](https://user-images.githubusercontent.com/15038280/110027074-87b19900-7cff-11eb-979b-df02e8cd757e.png)

**Comment by runninghsus** [comment]
Hi @calebvogt 

the second box is only up to Desktop/
whereas the fourth box is selecting the sub-directories bsoid_test or bsoid_test2 etc
it automatically takes in all the h5 files in that folder.

let me know if you have any other questions.

**Comment by runninghsus** [comment]
see #33
