### ISSUE TITLE
LOCAL_CONFIG for human behavior classification

### ISSUE THREAD

**Issue by rim-yu** [YttriLab/B-SOID#28]
Hi. I am Rim Yu. 

Could I get LOCAL_CONFIG for human behavior classification shown in README.md? 

I would like to refer to that file. 

Please help me. :((

<img width="619" alt="210313" src="https://user-images.githubusercontent.com/58248838/111023393-2a62c980-841c-11eb-83f0-555e49497935.PNG">

**Comment by runninghsus** [comment]
You can use the app.
