### ISSUE TITLE
Is it correct to run this code? (B-SOID/bsoid_py/ main.py)

### ISSUE THREAD

**Issue by kangel429** [YttriLab/B-SOID#29]
hi
I want to classify animal behavior.
Is it correct to run this code? (B-SOID/bsoid_py/ main.py)

 I want to run it with python code.  not this method ( streamlit run bsoid_app.py)
actully I have already tried running this code. I was able to confirm that I successfully classify animal behavior.
but I'd like to see the behavior classification in real time, so,,could I get advice on how to do it?

Is it correct to run this code? (B-SOID/bsoid_py/ main.py)

please help me, ,thank you

**Comment by runninghsus** [comment]
see #24
