### ISSUE TITLE
Preprocessing issue with adp_filt in likelihoodprocessing.py

### ISSUE THREAD

**Issue by bkrall24** [YttriLab/B-SOID#30]
Hi! I'm having some trouble with some of my DLC csv files where the preprocessing step fails. Attached below is the error message that comes up. It appears to occur when then likelihood is low for one of the body parts in the file. I'm wondering if I can only include files where DLC was able to successfully track all the body parts across the video? Or is it possible to include files where the tracking fails at some points?

![image](https://user-images.githubusercontent.com/39782419/114739906-5329f780-9d17-11eb-9625-df47b0afafc0.png)

**Comment by kdslehmann** [comment]
I am having the same problem. I've tried including fewer body parts, but that doesn't seem to help. Do we need every one of the body parts tracked with a high likelihood before B-SOiD will work?

**Comment by kdslehmann** [comment]
I found answers on the Slack channel! It is an issue with body parts being occluded for a significant portion of the video. Have to either remove that body part or edit the code.

**Comment by runninghsus** [comment]
closed due to answer found on slack.
