### ISSUE TITLE
"Index error:list out of range" DLC .csv

### ISSUE THREAD

**Issue by MannyEsguerra** [YttriLab/B-SOID#33]
Just getting started with BSOID. I'm running bsoid_v2 in an Anaconda environment in Windows 10. In the browser interface, I can enter the paths to my DLC evaluation results (.csv) just fine, but when BSOID gets to the pose processing step I get this:

IndexError: list index out of range
Traceback:
File "f:\users\manny\anaconda3\envs\bsoid_v2\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "F:\Users\Manny\Documents\GitHub\B-SOID\bsoid_app.py", line 42, in <module>
    processor.compile_data()
File "F:\Users\Manny\Documents\GitHub\B-SOID\bsoid_app\data_preprocess.py", line 89, in compile_data
    file0_df = pd.read_csv(data_files[0], low_memory=False)

I have 4 poses in these files, is that the issue?

**Comment by runninghsus** [comment]
Hi @MannyEsguerra 

The root directory (third input box) should be B-SOiD Project directory
The drop-downs in the 5th and following boxes should be the session directories.

![bsoid_folder_structure](https://user-images.githubusercontent.com/40252919/132095739-d204a602-2af6-48a1-9e75-ee98be181aa3.jpg)

**Comment by sudawq** [comment]
Hi 
I have encountered the same problem as you. Have you solved it?

**Comment by MannyEsguerra** [comment]
Yes our particular issue was solved by selecting the correct analysis directory. It was specifically about pose processing step. However this "list out of range error" could occur at other places in the workflow as well for different reasons.
