### ISSUE TITLE
Failed on feature embedding. Try again by unchecking sidebar and rerunning extract features.

### ISSUE THREAD

**Issue by lior3032** [YttriLab/B-SOID#35]
Hello,

I've recently downloaded B-SOID and i tried working with several datasets, including the demo dataset and while i'm able to preprocess the data, I always receive the following error during extraction of features:

Failed on feature embedding. Try again by unchecking sidebar and rerunning extract features.

Your help would be appreciated )

**Comment by longddd-blink** [comment]
Hi, I also have this problem. How did you solve it？
