### ISSUE TITLE
Issue with libop264

### ISSUE THREAD

**Issue by baudyboy** [YttriLab/B-SOID#37]
Hi, 
I work on windows and I have installed and used B-SOID successfully.

I experienced an issue when generating snippets, with my videos but also with the examples video.

The following message pops-up:

libopenh264 @ 000002825bfd1540] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error

The result is that I have truncated videos in the mp4 folder and I cannot check the quality of the clustering.

My understanding is that the coded is not installed, and so I tried to install openh264. Unfortunately, I did not find an convincing explanation on how to do it. 

Does anyone have some feedback on this issue?

Thanks in advance

**Comment by runninghsus** [comment]
Hi @baudyboy 

Sorry for the delayed response. If you were able to generate the videos, then you can ignore the error. Some of the clusters can be short, so I would reduce the playback to make sense of the behavior.

I will reach out to you personally in terms of ways to deal with oversplitting.
