### ISSUE TITLE
Generalisation to a different number of body parts 

### ISSUE THREAD

**Issue by PolarBean** [YttriLab/B-SOID#4]
One thing I'd be interested in contributing is generalising the script so that users can define a different number of body parts than the six defaults (which may be useful for alternative camera angles or behaviours). Does this sound feasible to implement? if so I am happy to work on it.
thank you for your help!

**Comment by runninghsus** [comment]
It definitely is feasible to implement, collecting features based on what people have labeled (how is body length calculated in this user's set-up). We can talk more about this in a couple of weeks when 1.1 is out.
We can collaborate on the next few versions for sure! It'll be nice to have other people help make this better.
Thank you for showing interest in making this better!

Alex

**Comment by PolarBean** [comment]
Given the algorithm is unsupervised, I wonder if it would be valid to just calculate the pointwise distance between all coordinates and feed these into the next stage with no explicit body length feature. Looking forward to 1.1! 
all the best, 

Harry
