### ISSUE TITLE
problem with transferring variables from section to section in UI

### ISSUE THREAD

**Issue by WeissShahaf** [YttriLab/B-SOID#42]
OS: WIN10

command:
streamlit run bsoid_app.py

when trying to load SLEAP data, pre-processing stage works, but trying to advance to the next tick (extract and embed features) i get the following error

NameError: name 'working_dir' is not defined
Traceback:
File "h:\anaconda3\envs\bsoid_v2\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "E:\BSOID\bsoid_app.py", line 45, in <module>
    [_, _, framerate, _, _, _, processed_input_data, _] = load_data(working_dir, prefix)

if i try to fix working_dir in the code i get the same error with prefix, which cannot be fixed by assigning it in code.

Thanks,
Shahaf

**Comment by runninghsus** [comment]
Hi @WeissShahaf 

Click the load data and preprocess first. Follow the prompts. After you completed the steps and compiled the data, then you load previous iteration (i.e. workspace containing your data).

**Comment by WeissShahaf** [comment]
that results in the following error:
No such directory

FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
Traceback:
File "h:\anaconda3\envs\bsoid_v2\lib\site-packages\streamlit\script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "E:\BSOID\bsoid_app.py", line 24, in <module>
    working_dir, prefix = query_workspace()
File "E:\BSOID\bsoid_app\bsoid_utilities\load_workspace.py", line 21, in query_workspace
    files = [i for i in os.listdir(working_dir) if os.path.isfile(os.path.join(working_dir, i)) and \

but from a UI\ UX perspective. it makes no sense to start at tick mark 2. then deselect it and go one back.

**Comment by runninghsus** [comment]
Hi @WeissShahaf 

I agree that from a UI perspective it is not ideal.
This directory that you created to save the workspace
![image](https://user-images.githubusercontent.com/40252919/132095207-6331c692-32c9-4b1d-9c1e-ce05a54dce51.png)
should be copied and pasted to 
![image](https://user-images.githubusercontent.com/40252919/132095223-b957b379-3538-4236-9ce5-0bde0167987e.png)

and it'll load up the the workspace/model you desire

**Comment by WeissShahaf** [comment]
i can't even get there.
the error appears when i click on "load previous iteration" and i can't do anything else from there
![image](https://user-images.githubusercontent.com/45653608/132095404-dc69067f-2d3e-443a-a594-4e4f1119e563.png)

**Comment by runninghsus** [comment]
There's no box underneath where you can type?
Here is the identical error without me typing anything in the box.
![image](https://user-images.githubusercontent.com/40252919/132095523-1a87e232-fd85-4457-a07b-0769b23c057d.png)

**Comment by WeissShahaf** [comment]
nope. not for me. 
and if i try to go back to the load data screen i have to do everything all over again

is there a debug command that prints what's going on in the background to the command line?

**Comment by WeissShahaf** [comment]
after restarting the app, and multiple clicks on the empty field, i finally managed to write into it. not sure what was wrong.

but may i suggest reordering the UI, and not having the default next move result in an error on screen?
it's very confusing

**Comment by runninghsus** [comment]
ok
