### ISSUE TITLE
[libopenh264 @ 0000018ea0c2b9c0] Incorrect library version loaded Could not open codec 'libopenh264': Unspecified error

### ISSUE THREAD

**Issue by vickerse1** [YttriLab/B-SOID#45]
Hello,

I get this error while extracting frames, just before extracting video snippets:

-------------------
[libopenh264 @ 0000018ea0c2b9c0] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
------------------

Also, sometimes creation of the snippets fails and I get an index out of range error.

Can you help me? Are these issues potentially related?

Thanks,

Evan

**Comment by SorenHJ** [comment]
I am having a very similar error:

Failed to load OpenH264 library: openh264-1.8.0-win64.dll
        Please check environment and/or download library: https://github.com/cisco/openh264/releases

[libopenh264 @ 000002c604c42100] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error

Did you manage to find a solution? 

Best regards
Søren

**Comment by mfernandamirabile** [comment]
In my case, this error is not letting me run the code to record a pi camera, so I can't ignore it. Did you find the solution?

Best regards,
Maria Fernanda
