### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by Andy-Stew** [YttriLab/B-SOID#49]
Hi!

Just getting started with BSOID and consistently am running into an issue with pre-processing my data

Keep getting this error message

<img width="1034" alt="Screen Shot 2021-10-08 at 3 25 27 PM" src="https://user-images.githubusercontent.com/92182519/136614684-2859c9e7-d04e-47b2-95e4-46ef6a03bbf1.png"> 

Would love any guidance on this issue.

Running on macOS if that matters.

**Comment by Zch6666** [comment]
I am experiencing the same problem. Can you please tell me what to do to solve this problem?
