### ISSUE TITLE
[Feature request] B-SOID to Python

### ISSUE THREAD

**Issue by JensBlack** [YttriLab/B-SOID#5]
Hi,
beautiful preprint and really interesting tool. I was wandering if you are interested in porting B-SOID to Python to match the general open-source mentality in the DeepLabCut universe.
I haven't had an indepth look at your code yet, so excuse my naive perspective. Do you think this is a doable?
I will have a look on my own in the next few weeks but I would appreciate your comment on this.
thanks.

**Comment by runninghsus** [comment]
Hi @JensBlack 

We are in the processes of porting this to python. In addition, we are adding some new functionality while we port it. Keep in contact with us and we will release an update as soon as we submit our manuscript!

Alex

**Comment by JensBlack** [comment]
Thank you for your response. I will definetly stay tuned!
