### ISSUE TITLE
"List Index Out of Range" (Step: Generate video snippets for interpretation)

### ISSUE THREAD

**Issue by jkt6044** [YttriLab/B-SOID#57]
I have been encountering issues in the “Generate video snippets for interpretation” step of the B-SOiD Streamlit app where I cannot create an example video due to an error “list index out of range”. I’m currently using the same video I used in the earlier preprocessing stages to identify the features and clusters. I’ve also tried different syntax for specifying the sub-directory (ex. HL177\ instead of HL177) with no luck.

- Some screenshots of the B-SOiD interface and error:

![generate_video_snippets_for_interpretation1](https://user-images.githubusercontent.com/93558613/158459113-a06443b4-0069-42d3-8945-63c04dbed6cd.PNG)

Seems like the prediction went okay

![generate_video_snippets_for_interpretation2](https://user-images.githubusercontent.com/93558613/158459130-bcd99b47-78a5-4da7-9719-6ad393ef6e9b.PNG)

- Some screenshots of my current B-SOiD project directory and sub-directory (followed the instruction mentioned in issue #33):

Root project directory
![video_and_data_folder_directory1](https://user-images.githubusercontent.com/93558613/158458742-49bb7625-a19a-4995-ac48-2df08ca7e8e1.PNG)

Video and data directory I specified in B-SOiD interface:
![video_and_data_folder_directory2](https://user-images.githubusercontent.com/93558613/158458796-d9e8efca-a8f1-4d3f-b1d8-170dfb4f8bb3.PNG)

It is mentioned here (https://stackoverflow.com/questions/65157867/indexerror-list-index-out-of-range-in-python-with-opencv-and-facerecognition) that this issue could be related with OpenCV (cv2.imread) but not familiar with to diagnose the root of the problem.

- Other info:
Model in use: SLEAP
Environment: Win10 Enterprise 
CPU: Intel® Core™ i5-4590 CPU
RAM: 32GB

**Comment by runninghsus** [comment]
did you extract frames with the app? (toggle the "yes" to a "no" and extract first, sorry that part is confusing.)
the pngs/ folder in your screenshot should be populated with a subdirectory HL177_220118_OF... that contains frame1.png, frame2.png, etc.

**Comment by jkt6044** [comment]
Yes, it turned out that I didn't have the frames extracted prior to the making label predictions- hence my 'frames' directory was empty. I was able to generate the example videos as well. 

Thank you!
