### ISSUE TITLE
Multiple Licence Issue

### ISSUE THREAD

**Issue by cdrinbublexn** [YttriLab/B-SOID#6]
Hi,

There is currently 3 licenses referenced in this repo and I'm relatively lost on the one that apply on this project :
[LICENSE](../blob/master/LICENSE) states that the repo is under _GNU General Public License v3.0_,
but under the [License ](..#license) part of the README, it's stated that the project is licensed under the  _GNU Lesser General Public License v3.0_.
And at the end of the aforementioned part, the _GNU Affero General Public License v3.0_ is linked.

Thank you and hope you could help to clarify which license apply on this project.
Nolan

**Comment by runninghsus** [comment]
Hi Nolan,

Thank you for pointing that out! The license indeed is under GNU General Public License v3.0. I apologize for the ambiguity in the README.

Alex

**Comment by runninghsus** [comment]
Hi Nolan,

I notice that you are working for CDRIN! We welcome collaboration if you are interested in working together. In particular, we are interested to see the applications that come out of this.

Thanks again for your issue.

Alex
