### ISSUE TITLE
Feature: Google Colab: Consider using pandas mulitindex when using read_csv('DLC.csv')

### ISSUE THREAD

**Issue by JensBlack** [YttriLab/B-SOID#8]
**Disclaimer**
Again, I want to thank you first for shipping the whole Bsoid code into python. This must be alot of work. Creating a Google Colab version of it so everyone can test it right away was a brilliant move. As you asked me to give feedback on the process, I will do so. Saying that, I would completely understand if the 'Feature' I am writing about is not an actual improvement worth rewritting code for. I just want to share it, as I was struggling with pandas for quite some time and love to use it now.

**Feature**
While dropping columns from my 9 bodyparts dlc file, i noticed that you are not using multiindexing when you load the csv file from deeplabcut generated files (See screenshot). This results in pandas automatically assuming that the first row is the column header, but the rows underneath are data. As you are extracting features below, i guess you will encounter this issue and probably solved it by skipping 2 rows all the time.

The original dlc dataframe is created with a multiindex, something like this:

```
     scorer DLC_resnet50_DLStream9Mar26shuffle1_350000  ...                       
  bodyparts                                   nose   ...       tail_root 
     coords                                       x  ...    y         likelihood
       0                                 314.659546  ...  321.318329        1.0  
       1                                 316.235596  ...  320.991638        1.0
       2                                 316.770020  ...  320.810364        1.0
       3                                 316.974335  ...  320.441833        1.0
       4                                 318.530182  ...  319.821411        1.0
```

You can see this also in the index (first column) that actually includes a name for those levels of multiindex (scorer, bodyparts and cords). 

**Current import**

The current import looks like this:

```
      scorer  ... DLC_resnet50_DLStream9Mar26shuffle1_350000.26
0  bodyparts  ...                                      tail_tip
1     coords  ...                                    likelihood
2          0  ...                            0.9999994039535522
3          1  ...                            0.9999991655349731
4          2  ...                            0.9999995231628418
```
so every column has a header (DLC_resnet50_DLStream9Mar26shuffle1_350000 **.26** ) which also gets an additional ID at the end because panda columns need to be unique and then start with the first two rows (bodypart, x/y/likelihood)

**A possible improvement**

To load a csv file like this with a multiindex, you can simple add:

`currDf = pd.read_csv(filename,low_memory=False, header = [0,1,2])`

if you want to include the index column as the index (rather than creating a new one):

`currDf = pd.read_csv(filename,low_memory=False, header = [0,1,2], index_col=0)`

This allows you to manipulate and select the dataframe based on different levels, rather than full columns all the time.

This code for example is dropping the unnecessary bodyparts without knowing the first level name (scorer name).
`currDf = currDf.drop(columns=['neck', 'centroid', 'tail_tip'], level = 1)`

I find it very usefull when manipulating dataframes. 

**Screenshot**

![image](https://user-images.githubusercontent.com/44863941/78876689-ffc00200-7a4f-11ea-9106-3d567e0a019c.png)

**Comment by runninghsus** [comment]
Thank you for this improvement! And you are absolutely right, the purpose of Colab is not only to get it accessible to python users (and anyone with a google account), but also to get some feedback on possible user issues. I will definitely include these.

**Comment by AlexEMG** [comment]
Just saw this, perhaps it would make sense to just load the h5 (which decodes the metainformation correctly) and needs no edits at all), i.e.

`Data = pd.read_hdf(fn, "df_with_missing")`

Also, check out this notbook for loading DLC data and playing with it: https://github.com/DeepLabCut/DLCutils/blob/master/Demo_loadandanalyzeDLCdata.ipynb
